package manager.bean;

public class college {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.id
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    private String college;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.id
     *
     * @return the value of college.id
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.id
     *
     * @param id the value for college.id
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.college
     *
     * @return the value of college.college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.college
     *
     * @param college the value for college.college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    public college() {
    }

    public college(Integer id, String college) {
        this.id = id;
        this.college = college;
    }

    @Override
    public String toString() {
        return "college{" +
                "id=" + id +
                ", college='" + college + '\'' +
                '}';
    }
}