package manager.bean;

public class dormitoryDormNum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitorydormnum.dorm_num
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    private Integer dormNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitorydormnum.stratum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    private String stratum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitorydormnum.hasPeoIn
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    private Integer haspeoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitorydormnum.maxPeo_num
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    private Integer maxpeoNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitorydormnum.dorm_num
     *
     * @return the value of dormitorydormnum.dorm_num
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public Integer getDormNum() {
        return dormNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitorydormnum.dorm_num
     *
     * @param dormNum the value for dormitorydormnum.dorm_num
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public void setDormNum(Integer dormNum) {
        this.dormNum = dormNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitorydormnum.stratum
     *
     * @return the value of dormitorydormnum.stratum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public String getStratum() {
        return stratum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitorydormnum.stratum
     *
     * @param stratum the value for dormitorydormnum.stratum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public void setStratum(String stratum) {
        this.stratum = stratum == null ? null : stratum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitorydormnum.hasPeoIn
     *
     * @return the value of dormitorydormnum.hasPeoIn
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public Integer getHaspeoin() {
        return haspeoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitorydormnum.hasPeoIn
     *
     * @param haspeoin the value for dormitorydormnum.hasPeoIn
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public void setHaspeoin(Integer haspeoin) {
        this.haspeoin = haspeoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitorydormnum.maxPeo_num
     *
     * @return the value of dormitorydormnum.maxPeo_num
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public Integer getMaxpeoNum() {
        return maxpeoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitorydormnum.maxPeo_num
     *
     * @param maxpeoNum the value for dormitorydormnum.maxPeo_num
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public void setMaxpeoNum(Integer maxpeoNum) {
        this.maxpeoNum = maxpeoNum;
    }
}