package manager.bean;

import java.util.ArrayList;
import java.util.List;

public class dormitoryDormNumExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public dormitoryDormNumExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDormNumIsNull() {
            addCriterion("dorm_num is null");
            return (Criteria) this;
        }

        public Criteria andDormNumIsNotNull() {
            addCriterion("dorm_num is not null");
            return (Criteria) this;
        }

        public Criteria andDormNumEqualTo(Integer value) {
            addCriterion("dorm_num =", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumNotEqualTo(Integer value) {
            addCriterion("dorm_num <>", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumGreaterThan(Integer value) {
            addCriterion("dorm_num >", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("dorm_num >=", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumLessThan(Integer value) {
            addCriterion("dorm_num <", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumLessThanOrEqualTo(Integer value) {
            addCriterion("dorm_num <=", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumIn(List<Integer> values) {
            addCriterion("dorm_num in", values, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumNotIn(List<Integer> values) {
            addCriterion("dorm_num not in", values, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumBetween(Integer value1, Integer value2) {
            addCriterion("dorm_num between", value1, value2, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumNotBetween(Integer value1, Integer value2) {
            addCriterion("dorm_num not between", value1, value2, "dormNum");
            return (Criteria) this;
        }

        public Criteria andStratumIsNull() {
            addCriterion("stratum is null");
            return (Criteria) this;
        }

        public Criteria andStratumIsNotNull() {
            addCriterion("stratum is not null");
            return (Criteria) this;
        }

        public Criteria andStratumEqualTo(String value) {
            addCriterion("stratum =", value, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumNotEqualTo(String value) {
            addCriterion("stratum <>", value, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumGreaterThan(String value) {
            addCriterion("stratum >", value, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumGreaterThanOrEqualTo(String value) {
            addCriterion("stratum >=", value, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumLessThan(String value) {
            addCriterion("stratum <", value, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumLessThanOrEqualTo(String value) {
            addCriterion("stratum <=", value, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumLike(String value) {
            addCriterion("stratum like", value, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumNotLike(String value) {
            addCriterion("stratum not like", value, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumIn(List<String> values) {
            addCriterion("stratum in", values, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumNotIn(List<String> values) {
            addCriterion("stratum not in", values, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumBetween(String value1, String value2) {
            addCriterion("stratum between", value1, value2, "stratum");
            return (Criteria) this;
        }

        public Criteria andStratumNotBetween(String value1, String value2) {
            addCriterion("stratum not between", value1, value2, "stratum");
            return (Criteria) this;
        }

        public Criteria andHaspeoinIsNull() {
            addCriterion("hasPeoIn is null");
            return (Criteria) this;
        }

        public Criteria andHaspeoinIsNotNull() {
            addCriterion("hasPeoIn is not null");
            return (Criteria) this;
        }

        public Criteria andHaspeoinEqualTo(Integer value) {
            addCriterion("hasPeoIn =", value, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinNotEqualTo(Integer value) {
            addCriterion("hasPeoIn <>", value, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinGreaterThan(Integer value) {
            addCriterion("hasPeoIn >", value, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("hasPeoIn >=", value, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinLessThan(Integer value) {
            addCriterion("hasPeoIn <", value, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinLessThanOrEqualTo(Integer value) {
            addCriterion("hasPeoIn <=", value, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinIn(List<Integer> values) {
            addCriterion("hasPeoIn in", values, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinNotIn(List<Integer> values) {
            addCriterion("hasPeoIn not in", values, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinBetween(Integer value1, Integer value2) {
            addCriterion("hasPeoIn between", value1, value2, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andHaspeoinNotBetween(Integer value1, Integer value2) {
            addCriterion("hasPeoIn not between", value1, value2, "haspeoin");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumIsNull() {
            addCriterion("maxPeo_num is null");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumIsNotNull() {
            addCriterion("maxPeo_num is not null");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumEqualTo(Integer value) {
            addCriterion("maxPeo_num =", value, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumNotEqualTo(Integer value) {
            addCriterion("maxPeo_num <>", value, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumGreaterThan(Integer value) {
            addCriterion("maxPeo_num >", value, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("maxPeo_num >=", value, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumLessThan(Integer value) {
            addCriterion("maxPeo_num <", value, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumLessThanOrEqualTo(Integer value) {
            addCriterion("maxPeo_num <=", value, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumIn(List<Integer> values) {
            addCriterion("maxPeo_num in", values, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumNotIn(List<Integer> values) {
            addCriterion("maxPeo_num not in", values, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumBetween(Integer value1, Integer value2) {
            addCriterion("maxPeo_num between", value1, value2, "maxpeoNum");
            return (Criteria) this;
        }

        public Criteria andMaxpeoNumNotBetween(Integer value1, Integer value2) {
            addCriterion("maxPeo_num not between", value1, value2, "maxpeoNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dormitorydormnum
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 24 19:23:58 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}