package manager.bean;

public class faculties {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculties.professional_name
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    private String professionalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculties.faculties_name
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    private String facultiesName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculties.professional_name
     *
     * @return the value of faculties.professional_name
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    public String getProfessionalName() {
        return professionalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculties.professional_name
     *
     * @param professionalName the value for faculties.professional_name
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    public void setProfessionalName(String professionalName) {
        this.professionalName = professionalName == null ? null : professionalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculties.faculties_name
     *
     * @return the value of faculties.faculties_name
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    public String getFacultiesName() {
        return facultiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculties.faculties_name
     *
     * @param facultiesName the value for faculties.faculties_name
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    public void setFacultiesName(String facultiesName) {
        this.facultiesName = facultiesName == null ? null : facultiesName.trim();
    }

    public faculties(String professionalName, String facultiesName) {
        this.professionalName = professionalName;
        this.facultiesName = facultiesName;
    }

    public faculties() {
    }

    @Override
    public String toString() {
        return "faculties{" +
                "professionalName='" + professionalName + '\'' +
                ", facultiesName='" + facultiesName + '\'' +
                '}';
    }
}