package manager.bean;

public class maintenanceOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintenanceorder.orderID
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintenanceorder.user
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintenanceorder.dorm_num
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    private Integer dormNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintenanceorder.orderTitle
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    private String ordertitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintenanceorder.state
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintenanceorder.orderDescribe
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    private String orderdescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintenanceorder.orderID
     *
     * @return the value of maintenanceorder.orderID
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintenanceorder.orderID
     *
     * @param orderid the value for maintenanceorder.orderID
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintenanceorder.user
     *
     * @return the value of maintenanceorder.user
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintenanceorder.user
     *
     * @param user the value for maintenanceorder.user
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintenanceorder.dorm_num
     *
     * @return the value of maintenanceorder.dorm_num
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public Integer getDormNum() {
        return dormNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintenanceorder.dorm_num
     *
     * @param dormNum the value for maintenanceorder.dorm_num
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void setDormNum(Integer dormNum) {
        this.dormNum = dormNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintenanceorder.orderTitle
     *
     * @return the value of maintenanceorder.orderTitle
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public String getOrdertitle() {
        return ordertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintenanceorder.orderTitle
     *
     * @param ordertitle the value for maintenanceorder.orderTitle
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void setOrdertitle(String ordertitle) {
        this.ordertitle = ordertitle == null ? null : ordertitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintenanceorder.state
     *
     * @return the value of maintenanceorder.state
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintenanceorder.state
     *
     * @param state the value for maintenanceorder.state
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintenanceorder.orderDescribe
     *
     * @return the value of maintenanceorder.orderDescribe
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public String getOrderdescribe() {
        return orderdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintenanceorder.orderDescribe
     *
     * @param orderdescribe the value for maintenanceorder.orderDescribe
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void setOrderdescribe(String orderdescribe) {
        this.orderdescribe = orderdescribe == null ? null : orderdescribe.trim();
    }

    @Override
    public String toString() {
        return "maintenanceOrder{" +
                "orderid='" + orderid + '\'' +
                ", user='" + user + '\'' +
                ", dormNum=" + dormNum +
                ", ordertitle='" + ordertitle + '\'' +
                ", state=" + state +
                ", orderdescribe='" + orderdescribe + '\'' +
                '}';
    }
}