package manager.bean;

import java.util.ArrayList;
import java.util.List;

public class maintenanceOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public maintenanceOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderID is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderID =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderID <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderID >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderID >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderID <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderID <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderID like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderID not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderID in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderID not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderID between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderID not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andUserIsNull() {
            addCriterion("user is null");
            return (Criteria) this;
        }

        public Criteria andUserIsNotNull() {
            addCriterion("user is not null");
            return (Criteria) this;
        }

        public Criteria andUserEqualTo(String value) {
            addCriterion("user =", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotEqualTo(String value) {
            addCriterion("user <>", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThan(String value) {
            addCriterion("user >", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThanOrEqualTo(String value) {
            addCriterion("user >=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThan(String value) {
            addCriterion("user <", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThanOrEqualTo(String value) {
            addCriterion("user <=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLike(String value) {
            addCriterion("user like", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotLike(String value) {
            addCriterion("user not like", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserIn(List<String> values) {
            addCriterion("user in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotIn(List<String> values) {
            addCriterion("user not in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserBetween(String value1, String value2) {
            addCriterion("user between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotBetween(String value1, String value2) {
            addCriterion("user not between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andDormNumIsNull() {
            addCriterion("dorm_num is null");
            return (Criteria) this;
        }

        public Criteria andDormNumIsNotNull() {
            addCriterion("dorm_num is not null");
            return (Criteria) this;
        }

        public Criteria andDormNumEqualTo(Integer value) {
            addCriterion("dorm_num =", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumNotEqualTo(Integer value) {
            addCriterion("dorm_num <>", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumGreaterThan(Integer value) {
            addCriterion("dorm_num >", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("dorm_num >=", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumLessThan(Integer value) {
            addCriterion("dorm_num <", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumLessThanOrEqualTo(Integer value) {
            addCriterion("dorm_num <=", value, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumIn(List<Integer> values) {
            addCriterion("dorm_num in", values, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumNotIn(List<Integer> values) {
            addCriterion("dorm_num not in", values, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumBetween(Integer value1, Integer value2) {
            addCriterion("dorm_num between", value1, value2, "dormNum");
            return (Criteria) this;
        }

        public Criteria andDormNumNotBetween(Integer value1, Integer value2) {
            addCriterion("dorm_num not between", value1, value2, "dormNum");
            return (Criteria) this;
        }

        public Criteria andOrdertitleIsNull() {
            addCriterion("orderTitle is null");
            return (Criteria) this;
        }

        public Criteria andOrdertitleIsNotNull() {
            addCriterion("orderTitle is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertitleEqualTo(String value) {
            addCriterion("orderTitle =", value, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleNotEqualTo(String value) {
            addCriterion("orderTitle <>", value, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleGreaterThan(String value) {
            addCriterion("orderTitle >", value, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleGreaterThanOrEqualTo(String value) {
            addCriterion("orderTitle >=", value, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleLessThan(String value) {
            addCriterion("orderTitle <", value, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleLessThanOrEqualTo(String value) {
            addCriterion("orderTitle <=", value, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleLike(String value) {
            addCriterion("orderTitle like", value, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleNotLike(String value) {
            addCriterion("orderTitle not like", value, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleIn(List<String> values) {
            addCriterion("orderTitle in", values, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleNotIn(List<String> values) {
            addCriterion("orderTitle not in", values, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleBetween(String value1, String value2) {
            addCriterion("orderTitle between", value1, value2, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andOrdertitleNotBetween(String value1, String value2) {
            addCriterion("orderTitle not between", value1, value2, "ordertitle");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeIsNull() {
            addCriterion("orderDescribe is null");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeIsNotNull() {
            addCriterion("orderDescribe is not null");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeEqualTo(String value) {
            addCriterion("orderDescribe =", value, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeNotEqualTo(String value) {
            addCriterion("orderDescribe <>", value, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeGreaterThan(String value) {
            addCriterion("orderDescribe >", value, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeGreaterThanOrEqualTo(String value) {
            addCriterion("orderDescribe >=", value, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeLessThan(String value) {
            addCriterion("orderDescribe <", value, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeLessThanOrEqualTo(String value) {
            addCriterion("orderDescribe <=", value, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeLike(String value) {
            addCriterion("orderDescribe like", value, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeNotLike(String value) {
            addCriterion("orderDescribe not like", value, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeIn(List<String> values) {
            addCriterion("orderDescribe in", values, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeNotIn(List<String> values) {
            addCriterion("orderDescribe not in", values, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeBetween(String value1, String value2) {
            addCriterion("orderDescribe between", value1, value2, "orderdescribe");
            return (Criteria) this;
        }

        public Criteria andOrderdescribeNotBetween(String value1, String value2) {
            addCriterion("orderDescribe not between", value1, value2, "orderdescribe");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table maintenanceorder
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 30 16:41:04 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}