package manager.bean;

public class ManagerUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.id
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.username
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.password
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.id
     *
     * @return the value of manager_user.id
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.id
     *
     * @param id the value for manager_user.id
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.username
     *
     * @return the value of manager_user.username
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.username
     *
     * @param username the value for manager_user.username
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.password
     *
     * @return the value of manager_user.password
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.password
     *
     * @param password the value for manager_user.password
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}