package manager.bean;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.num
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.professional
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private String professional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.faculties
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private String faculties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phoneNum
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.dorm_num
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    private Integer dormNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.num
     *
     * @return the value of student.num
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.num
     *
     * @param num the value for student.num
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.professional
     *
     * @return the value of student.professional
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public String getProfessional() {
        return professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.professional
     *
     * @param professional the value for student.professional
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setProfessional(String professional) {
        this.professional = professional == null ? null : professional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.faculties
     *
     * @return the value of student.faculties
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public String getFaculties() {
        return faculties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.faculties
     *
     * @param faculties the value for student.faculties
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setFaculties(String faculties) {
        this.faculties = faculties == null ? null : faculties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phoneNum
     *
     * @return the value of student.phoneNum
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phoneNum
     *
     * @param phonenum the value for student.phoneNum
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.dorm_num
     *
     * @return the value of student.dorm_num
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public Integer getDormNum() {
        return dormNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.dorm_num
     *
     * @param dormNum the value for student.dorm_num
     *
     * @mbg.generated Fri Sep 24 19:25:13 CST 2021
     */
    public void setDormNum(Integer dormNum) {
        this.dormNum = dormNum;
    }

    public Student(Integer id, String num, String name, String gender, Integer grade, String professional, String faculties, String phonenum, Integer dormNum) {
        this.id = id;
        this.num = num;
        this.name = name;
        this.gender = gender;
        this.grade = grade;
        this.professional = professional;
        this.faculties = faculties;
        this.phonenum = phonenum;
        this.dormNum = dormNum;
    }

    public Student() {
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", num='" + num + '\'' +
                ", name='" + name + '\'' +
                ", gender='" + gender + '\'' +
                ", grade=" + grade +
                ", professional='" + professional + '\'' +
                ", faculties='" + faculties + '\'' +
                ", phonenum='" + phonenum + '\'' +
                ", dormNum=" + dormNum +
                '}';
    }
}