package manager.dao;

import java.util.List;
import manager.bean.college;
import manager.bean.collegeExample;
import org.apache.ibatis.annotations.Param;

public interface collegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    long countByExample(collegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    int deleteByExample(collegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    int insert(college record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    int insertSelective(college record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    List<college> selectByExample(collegeExample example);

    college selectById(int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") college record, @Param("example") collegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Sun Sep 12 11:48:21 CST 2021
     */
    int updateByExample(@Param("record") college record, @Param("example") collegeExample example);
}