package manager.dao;

import java.util.List;
import manager.bean.dormitoryDormNum;
import manager.bean.dormitoryDormNumExample;
import org.apache.ibatis.annotations.Param;

public interface dormitoryDormNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    long countByExample(dormitoryDormNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    int deleteByExample(dormitoryDormNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    int deleteByPrimaryKey(Integer dormNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    int insert(dormitoryDormNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    int insertSelective(dormitoryDormNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    List<dormitoryDormNum> selectByExample(dormitoryDormNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    dormitoryDormNum selectByPrimaryKey(Integer dormNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    int updateByExampleSelective(@Param("record") dormitoryDormNum record, @Param("example") dormitoryDormNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    int updateByExample(@Param("record") dormitoryDormNum record, @Param("example") dormitoryDormNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    int updateByPrimaryKeySelective(dormitoryDormNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitorydormnum
     *
     * @mbg.generated Fri Sep 24 19:23:58 CST 2021
     */
    int updateByPrimaryKey(dormitoryDormNum record);

}