package manager.dao;

import java.util.List;
import manager.bean.faculties;
import manager.bean.facultiesExample;
import org.apache.ibatis.annotations.Param;

public interface facultiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculties
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    long countByExample(facultiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculties
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    int deleteByExample(facultiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculties
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    int insert(faculties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculties
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    int insertSelective(faculties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculties
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    List<faculties> selectByExample(facultiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculties
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    int updateByExampleSelective(@Param("record") faculties record, @Param("example") facultiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculties
     *
     * @mbg.generated Mon Sep 06 20:23:04 CST 2021
     */
    int updateByExample(@Param("record") faculties record, @Param("example") facultiesExample example);


    List<faculties> selectByCollegeId(int id);



}