package manager.dao;

import java.util.List;
import manager.bean.maintenanceOrder;
import manager.bean.maintenanceOrderExample;
import org.apache.ibatis.annotations.Param;

public interface maintenanceOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    long countByExample(maintenanceOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    int deleteByExample(maintenanceOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    int insert(maintenanceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    int insertSelective(maintenanceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    List<maintenanceOrder> selectByExample(maintenanceOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    maintenanceOrder selectByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    int updateByExampleSelective(@Param("record") maintenanceOrder record, @Param("example") maintenanceOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    int updateByExample(@Param("record") maintenanceOrder record, @Param("example") maintenanceOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    int updateByPrimaryKeySelective(maintenanceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceorder
     *
     * @mbg.generated Thu Sep 30 16:41:04 CST 2021
     */
    int updateByPrimaryKey(maintenanceOrder record);
}