package manager.dao;

import java.util.List;
import manager.bean.ManagerUser;
import manager.bean.ManagerUserExample;
import org.apache.ibatis.annotations.Param;

public interface ManagerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    long countByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    int deleteByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    int insert(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    int insertSelective(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    List<ManagerUser> selectByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    ManagerUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    int updateByExampleSelective(@Param("record") ManagerUser record, @Param("example") ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    int updateByExample(@Param("record") ManagerUser record, @Param("example") ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    int updateByPrimaryKeySelective(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbg.generated Sun Sep 26 19:20:40 CST 2021
     */
    int updateByPrimaryKey(ManagerUser record);
}